# Site settings
title: Kristin Salomon
description: hardware/electrical engineer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ksalomon.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kristin Salomon
user_description: I'm a hardware engineer with experience in consumer product design and embedded firmware development looking for my next adventure. Get in touch!
user_title: hardware/electrical engineer
email: kristin@ksalomon.com
# twitter_username: lorem_ipsum
github_username:  _ksalomon
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
